#!/usr/bin/python3

import socket, select, queue
from queue import Queue
from time import sleep

HOST = '127.0.0.1'
PORT = 7000
inputs = []
outputs = []

msg_queue = {}

readable = []
writable = []

def _init_server():
    server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    server.bind((HOST, PORT))
    server.listen(5)
    inputs.append(server)


def _add_sock_msg_queue(sock):
    connection, client_address = sock.accept()
    connection.setblocking(0)
    inputs.append(connection)
    msg_queue[connection] = Queue()


def _recv_line(sock):
    global readable
    buf = b''
    _update_socket_status()
    i = 0
    while sock in readable:
        i += 1
        c = sock.recv(16)
        buf += c
        _update_socket_status()
        # idk why but works
        sleep(0.01)
        if buf == b'':
            break
    print(buf)
    return buf


def _recv_data(sock):
    try:
        data = _recv_line(sock)
        if data:
            msg_queue[sock].put(data)
    except:
        pass


def _update_io_queue(sock):
    if sock not in outputs:
        outputs.append(sock)
    else:
        if sock in outputs:
            outputs.remove(sock)
        inputs.remove(sock)
        sock.close()
        del msg_queue[sock]


def _send_private_msg(sock):
    try:
        next_msg = msg_queue[sock].get_nowait()
    except Exception as e:
        if sock in outputs:
            outputs.remove(sock)
    else:
        sock.send(b"/error\n")


def _update_socket_status():
    global readable
    global writable
    readable, writable, exceptional = select.select(inputs, outputs, [], 0.5)


def main():
    global writable
    global readable
    _init_server()
    while inputs:
        _update_socket_status()
        for s in readable:
            if s is inputs[0]:
                _add_sock_msg_queue(s)
            else:
                _recv_data(s)
                _update_io_queue(s)
        for s in writable:
            _send_private_msg(s)


if __name__ == '__main__':
    main()

